// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Data;

#nullable disable

namespace ProductsAPI.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20260203173111_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductsAPI.Models.ProductsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contractor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductsModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contractor = "Outsource",
                            ProductLabel = "Levi",
                            ProductType = "Jeans",
                            Quantity = 90
                        },
                        new
                        {
                            Id = 2,
                            Contractor = "Outsource",
                            ProductLabel = "Next",
                            ProductType = "T-Shirt",
                            Quantity = 38
                        },
                        new
                        {
                            Id = 3,
                            Contractor = "InHouse",
                            ProductLabel = "RiverIsland",
                            ProductType = "Jacket",
                            Quantity = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
